// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAUpqFcSW_584vn5qv2_MfHBzi26Aw_u0',
    appId: '1:725846260619:web:4536978988658dba038d8e',
    messagingSenderId: '725846260619',
    projectId: 'teambobcarpark-eb03e',
    authDomain: 'teambobcarpark-eb03e.firebaseapp.com',
    storageBucket: 'teambobcarpark-eb03e.appspot.com',
    measurementId: 'G-RJ44KF1VVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkH07jgmLPX2BfWR4r80bNZxHkF5i5c4',
    appId: '1:725846260619:android:18e3a916b8f25823038d8e',
    messagingSenderId: '725846260619',
    projectId: 'teambobcarpark-eb03e',
    storageBucket: 'teambobcarpark-eb03e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCnItSJ8wlKiKIbfedYUuXMDFBUA03rDQ',
    appId: '1:725846260619:ios:c8078f6ab33787ea038d8e',
    messagingSenderId: '725846260619',
    projectId: 'teambobcarpark-eb03e',
    storageBucket: 'teambobcarpark-eb03e.appspot.com',
    iosBundleId: 'com.teambobcarpark.search',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCnItSJ8wlKiKIbfedYUuXMDFBUA03rDQ',
    appId: '1:725846260619:ios:858c7f153f8b1318038d8e',
    messagingSenderId: '725846260619',
    projectId: 'teambobcarpark-eb03e',
    storageBucket: 'teambobcarpark-eb03e.appspot.com',
    iosBundleId: 'com.example.search.RunnerTests',
  );
}
